Сделано 2 задание
Krayseer/contacter pull request #12
Opened 2023-11-23 17:49 UTC by Krayseer

2023-12-09 20:10 UTC, vpyzhyanov requested changes
1. Не исправлены замечания из предыдущей задачи
2. **Нет тестов на новые функции.** Ребята, как так???
3. Перешли на тёмную сторону ООП

Снял баллы за git из-за этого:

![image](https://github.com/Krayseer/contacter/assets/71599019/284dbc5f-7f9d-4e56-9762-91158700c242)

Похоже за это надо снять баллы за гит (выделено красным). Тут можно предъявить неиспользование веток (раз ветка не попала в итоговый код), работу только одного человека (раз только ваша ветка была смёрджена в task2)
То, что выделено жёлтым выглядит очень подозрительно. У двух разных людей абсолютно одинаковые комментарии к коммиту. Либо это комментарии не соответствующие действительности, либо это попытка симулировать работу двух человек над одной задачей, когда фактически её делал только один человек.

2023-12-09 20:10 UTC, vpyzhyanov commented on src/main/java/ru/anykeyers/domain/Contact.java
> +    private boolean block;
хорошо бы сделать отступ перед конструктором, чтобы поле с ним не сливалось

2023-12-09 20:10 UTC, vpyzhyanov commented on src/main/java/ru/anykeyers/domain/Contact.java
> +    private boolean block;
boolean свойства принято называть с помощью вопросительных глаголов, "is", "has" или простых страдательных глаголов типа "enabled". В данном случае можно назвать поле "bloked" или "isBlocked"

2023-12-09 20:10 UTC, vpyzhyanov commented on src/main/java/ru/anykeyers/domain/Contact.java
> +        StringBuilder builder = new StringBuilder();
Разве вы не видите предупреждение в IDEA? Она говорит вам, что тут можно использовать просто String. И она права.

2023-12-09 20:10 UTC, vpyzhyanov commented on src/main/java/ru/anykeyers/domain/Contact.java
> +    public String getInfo() {
По хорошему форматированием в читаемое строковое представление должен заниматься отдельный класс. Так можно делать только, если вы хотите сделать настоящую инкапсуляцию, но вы даже не пытались. Так что однозначно в отдельный класс.

Тут я немного придираюсь, т.к. такая задача может и не стоит вынесения в отдельный класс, но это важно в учебных целях, чтобы вы задумывались о том, что разные задачи нужно разделять по разным классам. Так что надо исправить.

2023-12-09 20:10 UTC, vpyzhyanov commented on src/main/java/ru/anykeyers/domain/Contact.java
> +                .append("\nНомер телефона: ").append(phoneNumber != null ? phoneNumber : StringUtils.EMPTY)
ставить символ перехода на следующую строку **в начале строки** - дурной тон. Он должен быть в конце строки. Рекомендую вам использовать фичу java17 для вывода многострочного текста с подстановкой параметров.

2023-12-09 20:10 UTC, vpyzhyanov commented on src/main/java/ru/anykeyers/domain/Contact.java
> +                Objects.equals(username, contact.getUsername()) &&
метод реализован по прежнему некорректно. Это замечание было в первой задаче! Пожалуйста, больше не допускайте неисправленных замечаний из предыдущей задачи.

2023-12-09 20:10 UTC, vpyzhyanov commented on src/main/java/ru/anykeyers/domain/Group.java
> +        return String.format("Название: %s. Количество участников: %s.", name, contacts == null ? 0 : contacts.size());
длинная строчка, перенесите все параметры на следующую строку. Особенно с учётом того, что в одном параметре условие.

Не увлекайтесь однострочным программированием, строчки - бесплатные)

**ВАЖНО! В вашем случае допускать null является большой ошибкой**, особенно если учесть то, что вам ничего не стоит гарантировать, что тут будет не null. Предлагаю вам полностью избавиться от null. null - это потенциальный неожиданный NullPointerException

2023-12-09 20:10 UTC, vpyzhyanov commented on src/main/java/ru/anykeyers/domain/User.java
> +    private String editInfo;
Насколько я понял это поле - является параметром, используемым при обработке состояния. Добро пожаловать на тёмную сторону ООП, ваш класс `User` решает несколько задач. Явно тут нужен ещё один класс. Как думаете, какой?

2023-12-09 20:10 UTC, vpyzhyanov commented on src/main/java/ru/anykeyers/domain/User.java
> +                && Objects.equals(editInfo, user.getEditInfo())
метод equals реализован некорректно! Вы правда считаете, что пользователь, у которого изменилось состояние - это уже другой пользователь?!

2023-12-09 20:10 UTC, vpyzhyanov commented on src/main/java/ru/anykeyers/domain/kinds/GroupEditKind.java
> +public final class GroupEditKind {
описание и название класса не соответствуют друг другу. Название говорит про какой-то вид группы, а описание про аргументы. А значения - вообще числа. Я ничего не понял

2023-12-09 20:10 UTC, vpyzhyanov commented on src/main/java/ru/anykeyers/domain/kinds/SearchKind.java
> +public final class SearchKind {
аналогично

2023-12-09 20:10 UTC, vpyzhyanov commented on src/main/java/ru/anykeyers/domain/kinds/contact/ContactEditBlockKind.java
> +public final class ContactEditBlockKind {
все остальные тоже

2023-12-09 20:10 UTC, vpyzhyanov commented on src/main/java/ru/anykeyers/factories/StateProcessorFactory.java
> +            case FUNCTION -> {
не очень удачное имя выбрали. Обычно под функцией понимают функцию, а не одно из состояний. Ну и это очень общий термин, сложно понять что вы тут имеете в виду. Благо есть JavaDoc, который поясняет. Но лучше отразить это пояснение в имени `(поиск, фильтр, сортировка)`, и, желательно, без слова function.

2023-12-09 20:10 UTC, vpyzhyanov commented on src/main/java/ru/anykeyers/factories/StateProcessorFactory.java
> +                SearchService searchService = new SearchServiceImpl(contactRepository, groupRepository);
похоже я только сейчас заметил существенную просадку по производительности и памяти. Зачем вы **каждый раз** и **на каждый запрос** создаёте сервисы и репозитории? Да ещё и обработчик состояния `ru.anykeyers.factories.StateProcessorFactory#createStateProcessorByType` оказывается тоже каждый раз создаётся заново! Не надо так. Создайте один раз и используйте. 

Например, все `StateProcessor` можно сложить в Map и доставать по типу состояния

2023-12-09 20:10 UTC, vpyzhyanov commented on src/main/java/ru/anykeyers/processors/states/impl/ContactStateProcessor.java
>              switch (field.toLowerCase()) {
странно цифру приводить к нижнему регистру)))

2023-12-09 20:10 UTC, vpyzhyanov commented on src/main/java/ru/anykeyers/processors/states/impl/ContactStateProcessor.java
> +            return messages.getMessageByKey("commons.bad-argument");
Замечание про messages не исправлено!

2023-12-09 20:10 UTC, vpyzhyanov commented on src/main/java/ru/anykeyers/processors/states/impl/FunctionalStateProcessor.java
> +        messages = new Messages();
очередной раз читается один и тот же файл. Нехорошо

2023-12-09 20:10 UTC, vpyzhyanov commented on src/main/java/ru/anykeyers/processors/states/impl/FunctionalStateProcessor.java
> +public class FunctionalStateProcessor extends BaseStateProcessor {
аналогично: выбрано неудачное имя с использованием слова `Functional`

2023-12-09 20:10 UTC, vpyzhyanov commented on src/main/java/ru/anykeyers/processors/states/impl/FunctionalStateProcessor.java
> +            switch (message.toLowerCase()) {
снова цифры к нижнему регистру приводятся

2023-12-09 20:10 UTC, vpyzhyanov commented on src/main/java/ru/anykeyers/processors/states/impl/FunctionalStateProcessor.java
> +        registerSortCommands();
молодцы, что разбили на методы по смыслу

2023-12-09 20:10 UTC, vpyzhyanov commented on src/main/java/ru/anykeyers/repositories/file/FileContactRepository.java
> +        if (contacts == null) {
1. В JavaDoc метода `findByUsername` нет ни слова о том, что он возвращает null
2. Нет никого смысла возвращать null, когда вы используете коллекцию. Возвращайте **пустую коллекцию**. В данном случае `Set.of()`
3. Всегда старайтесь избегать null.

2023-12-09 20:10 UTC, vpyzhyanov commented on src/main/java/ru/anykeyers/repositories/file/FileContactRepository.java
> +            return null;
в этом случае лучше использовать Optional, он создан как раз для того, чтобы методы его возвращали, для корректной и удобной обработки null значений

2023-12-09 20:10 UTC, vpyzhyanov commented on src/main/java/ru/anykeyers/repositories/file/FileContactRepository.java
> +            return null;
всё аналогично

2023-12-09 20:10 UTC, vpyzhyanov commented on src/main/java/ru/anykeyers/repositories/file/FileContactRepository.java
>      public Contact findByUsernameAndPhoneNumber(String username, String phoneNumber) {
в таких случая принято называть метод с использованием слова `get`. Имя `find` уместно только тогда, когда вы делаете **поиск** и возвращаете коллекцию значений.

2023-12-09 20:10 UTC, vpyzhyanov commented on src/main/java/ru/anykeyers/repositories/file/FileContactRepository.java
>      public Contact findByUsernameAndName(String username, String name) {
в таких случая принято называть метод с использованием слова `get`. Имя `find` уместно только тогда, когда вы делаете **поиск** и возвращаете коллекцию значений.

2023-12-09 20:10 UTC, vpyzhyanov commented on src/main/java/ru/anykeyers/repositories/file/FileContactRepository.java
> +            return null;
аналогично

2023-12-09 20:10 UTC, vpyzhyanov commented on src/main/java/ru/anykeyers/repositories/file/FileContactRepository.java
> +        if (contacts == null) {
аналогично

2023-12-09 20:10 UTC, vpyzhyanov commented on src/main/java/ru/anykeyers/repositories/file/FileGroupRepository.java
> +        if (groups == null) {
аналогично

2023-12-09 20:10 UTC, vpyzhyanov commented on src/main/java/ru/anykeyers/repositories/file/FileContactRepository.java
>          for (Contact contact : findByUsername(username)) {
2 раза подряд вызывается одна и та же функция

2023-12-09 20:10 UTC, vpyzhyanov commented on src/main/java/ru/anykeyers/repositories/file/FileGroupRepository.java
>          for (Group group : findByUsername(username)) {
2 раза подряд вызывается одна и та же функция

2023-12-09 20:10 UTC, vpyzhyanov commented on src/main/java/ru/anykeyers/repositories/file/parsers/FileContactParser.java
>          StringBuilder builder = new StringBuilder();
не вполне уместное использование `StringBuilder`. Его нужно использовать только тогда, когда у вас очень много данных и вы заполняете их в цикле. Во всех остальных случаях надо испольозовать String. Оптимизатор Java сделает свою магию и обычная строка будет работать гораздо эффективнее

2023-12-09 20:10 UTC, vpyzhyanov commented on src/main/java/ru/anykeyers/repositories/file/parsers/FileContactParser.java
>      public String parseTo(Contact object) {
замечания про имена методов и класса **из предыдущей задачи** не исправлены!!!

2023-12-09 20:10 UTC, vpyzhyanov commented on src/main/java/ru/anykeyers/repositories/file/parsers/FileContactParser.java
> +                    contact.setBlock(Objects.equals(value, "true"));
`Boolean.parseBoolean(value)`

2023-12-09 20:10 UTC, vpyzhyanov commented on src/main/java/ru/anykeyers/repositories/file/parsers/FileUserParser.java
> +                .append(";edit_info=").append(object.getEditInfo())
Зачем вам выгружать состояние? Какую задачу вы этим решаете?

Теперь я знаю как сломать ваше приложение)))) Достаточно сделать экспорт во время какого-то сложного состояния. А потом сделать импорт и с высокой долей вероятности мы окажемся в ситуации, когда не сможем выйти из этого состояния. Ну или получим некорректное поведение с некорректными ответами.

2023-12-09 20:10 UTC, vpyzhyanov commented on src/main/java/ru/anykeyers/services/FilterService.java
> + * Интерфейс сервиса для фильтрации контактов
1. не надо воды, это не диплом, все и так видят, что это интерфейс по ключевому слову `interface`
2. Описание не соответствует имени интерфейса. Название уж очень общее. Что-то в стиле `public interface Service`, т.е. совершенно невозможно догадаться что он фильтрует
3. Судя по описанию метод должен называться `FilterContactService`

2023-12-09 20:10 UTC, vpyzhyanov commented on src/main/java/ru/anykeyers/services/FilterService.java
> +     * @return результат фильтрации контактов
атрибут `@return` нужен для того, чтобы указать конкретные возвращаемые значения, если это возможно, или описание в каком виде возвращаются значения. Вы же использовали атрибут не по назначению, написали что-то в стиле "спасибо КЭП". А на самом деле вообще непонятно что же это за `результат фильтрации контактов` и почему он в виде строки.

P.S. Если не можете написать полезную информацию, ничего не пишите, даже сам `@return`.

2023-12-09 20:10 UTC, vpyzhyanov commented on src/main/java/ru/anykeyers/services/SearchService.java
> +public interface SearchService {
аналогично

2023-12-09 20:10 UTC, vpyzhyanov commented on src/main/java/ru/anykeyers/services/SearchService.java
> +     * @return список контактов
странно, что они в виде строки. Я бы ожидал коллекцию контактов. Подозреваю что вы путаете фильтрацию с форматированнием. Отсюда подозреваю вас в переходе на тёмную сторону ООП.

2023-12-09 20:10 UTC, vpyzhyanov commented on src/main/java/ru/anykeyers/services/SortService.java
> +public interface SortService {
все замечания аналогичные

2023-12-09 20:10 UTC, vpyzhyanov commented on src/main/java/ru/anykeyers/services/SortService.java
> +    String sortByUserStateAndKind(User user, String value);
здесь тоже смешали сортировку с форматированнием в строку

2023-12-09 20:10 UTC, vpyzhyanov commented on src/main/java/ru/anykeyers/services/impl/FilterServiceImpl.java
> +        this.messages = new Messages();
очередное считывание одного и того же файла

2023-12-09 20:10 UTC, vpyzhyanov commented on src/main/java/ru/anykeyers/services/impl/FilterServiceImpl.java
> +                return contact -> contact.getGender() != null && contact.getGender().equals(Gender.MAN);
`&& ... ` лучше перенести на следующую строку

2023-12-09 20:10 UTC, vpyzhyanov commented on src/main/java/ru/anykeyers/services/impl/FilterServiceImpl.java
> +                return contact -> contact.getGender() != null && contact.getGender().equals(Gender.WOMAN);
`&& ...`  лучше перенести на следующую строку

2023-12-09 20:10 UTC, vpyzhyanov commented on src/main/java/ru/anykeyers/services/impl/SearchServiceImpl.java
> +                    .collect(Collectors.joining("\n\n"));
совершенно точно этот класс перегружен функционалом

2023-12-09 20:10 UTC, vpyzhyanov commented on src/main/java/ru/anykeyers/services/impl/SearchServiceImpl.java
> +     * @return результат поиска
спасибо КЭП)))

2023-12-09 20:10 UTC, vpyzhyanov commented on src/main/java/ru/anykeyers/services/impl/SearchServiceImpl.java
> +                    .collect(Collectors.joining("\n\n"));
совершенно точно этот класс перегружен функционалом

2023-12-09 20:10 UTC, vpyzhyanov commented on src/main/java/ru/anykeyers/services/impl/SortServiceImpl.java
> +                .collect(Collectors.joining("\n\n"));
совершенно точно этот класс перегружен функционалом

2023-12-20 13:44 UTC, vpyzhyanov commented on src/main/java/ru/anykeyers/domain/User.java
> +    private String editInfo;
Нет ответа!!!

2023-12-20 14:17 UTC, Krayseer commented on src/main/java/ru/anykeyers/domain/User.java
> +    private String editInfo;
Добавил сервис UserStateService для работы с состояниями пользователя

2023-12-20 14:17 UTC, Krayseer commented on src/main/java/ru/anykeyers/domain/Contact.java
> +    private boolean block;
сделано

2023-12-20 14:17 UTC, Krayseer commented on src/main/java/ru/anykeyers/domain/Contact.java
> +    private boolean block;
исправлено

2023-12-20 14:17 UTC, Krayseer commented on src/main/java/ru/anykeyers/domain/Contact.java
> +        StringBuilder builder = new StringBuilder();
убрано в UiContactMapper

2023-12-20 14:17 UTC, Krayseer commented on src/main/java/ru/anykeyers/domain/Contact.java
> +    public String getInfo() {
Убрано в UiContactMapper

2023-12-20 14:18 UTC, Krayseer commented on src/main/java/ru/anykeyers/domain/Contact.java
> +                .append("\nНомер телефона: ").append(phoneNumber != null ? phoneNumber : StringUtils.EMPTY)
исправили, спасибо

2023-12-20 14:18 UTC, Krayseer commented on src/main/java/ru/anykeyers/domain/Contact.java
> +                Objects.equals(username, contact.getUsername()) &&
теперь там только id контакта

2023-12-20 14:18 UTC, Krayseer commented on src/main/java/ru/anykeyers/domain/Group.java
> +        return String.format("Название: %s. Количество участников: %s.", name, contacts == null ? 0 : contacts.size());
исправили недочет

2023-12-20 14:18 UTC, Krayseer commented on src/main/java/ru/anykeyers/domain/User.java
> +                && Objects.equals(editInfo, user.getEditInfo())
теперь там только id

2023-12-20 14:19 UTC, Krayseer commented on src/main/java/ru/anykeyers/domain/kinds/GroupEditKind.java
> +public final class GroupEditKind {
Этот и все следующие классы по типу этого были переименованы, добавлен новый javadoc

2023-12-20 14:19 UTC, Krayseer commented on src/main/java/ru/anykeyers/factories/StateProcessorFactory.java
> +            case FUNCTION -> {
Исправили на Operation(выполняемая операция)

2023-12-20 14:19 UTC, Krayseer commented on src/main/java/ru/anykeyers/factories/StateProcessorFactory.java
> +                SearchService searchService = new SearchServiceImpl(contactRepository, groupRepository);
сделано в новой версии

2023-12-20 14:20 UTC, Krayseer commented on src/main/java/ru/anykeyers/processors/states/impl/ContactStateProcessor.java
>              switch (field.toLowerCase()) {
и правда странно, убрано

2023-12-20 14:20 UTC, Krayseer commented on src/main/java/ru/anykeyers/processors/states/impl/ContactStateProcessor.java
> +            return messages.getMessageByKey("commons.bad-argument");
в новой версии исправлено

2023-12-20 14:20 UTC, Krayseer commented on src/main/java/ru/anykeyers/processors/states/impl/FunctionalStateProcessor.java
> +public class FunctionalStateProcessor extends BaseStateProcessor {
-> Operation

2023-12-20 14:20 UTC, Krayseer commented on src/main/java/ru/anykeyers/processors/states/impl/FunctionalStateProcessor.java
> +            switch (message.toLowerCase()) {
исправлено

2023-12-20 14:21 UTC, Krayseer commented on src/main/java/ru/anykeyers/repositories/file/FileContactRepository.java
> +        if (contacts == null) {
исправлено

2023-12-20 14:21 UTC, Krayseer commented on src/main/java/ru/anykeyers/repositories/file/FileContactRepository.java
> +            return null;
так и сделали

2023-12-20 14:22 UTC, Krayseer commented on src/main/java/ru/anykeyers/repositories/file/FileContactRepository.java
>      public Contact findByUsernameAndPhoneNumber(String username, String phoneNumber) {
исправили

2023-12-20 14:22 UTC, Krayseer commented on src/main/java/ru/anykeyers/repositories/file/FileContactRepository.java
>      public Contact findByUsernameAndName(String username, String name) {
исправили

2023-12-20 14:22 UTC, Krayseer commented on src/main/java/ru/anykeyers/repositories/file/FileContactRepository.java
>          for (Contact contact : findByUsername(username)) {
ошибка исправлена

2023-12-20 14:22 UTC, Krayseer commented on src/main/java/ru/anykeyers/repositories/file/parsers/FileContactParser.java
>          StringBuilder builder = new StringBuilder();
Исправлено

2023-12-20 14:22 UTC, Krayseer commented on src/main/java/ru/anykeyers/repositories/file/parsers/FileContactParser.java
>      public String parseTo(Contact object) {
исправлено в новой версии

2023-12-20 14:22 UTC, Krayseer commented on src/main/java/ru/anykeyers/repositories/file/parsers/FileContactParser.java
> +                    contact.setBlock(Objects.equals(value, "true"));
Поправили

2023-12-20 14:23 UTC, Krayseer commented on src/main/java/ru/anykeyers/repositories/file/parsers/FileUserParser.java
> +                .append(";edit_info=").append(object.getEditInfo())
Теперь состояние не выгружается а хранится в памяти в сервисе UserStateService

2023-12-20 14:23 UTC, Krayseer commented on src/main/java/ru/anykeyers/services/FilterService.java
> + * Интерфейс сервиса для фильтрации контактов
исправили

2023-12-20 14:23 UTC, Krayseer commented on src/main/java/ru/anykeyers/services/FilterService.java
> +     * @return результат фильтрации контактов
хорошо, в дальнейшем так и будем делать

2023-12-20 14:24 UTC, Krayseer commented on src/main/java/ru/anykeyers/services/SearchService.java
> +     * @return список контактов
Исправили сервисы, теперь они возвращают какие то данные (объекты, коллекции) или void

2023-12-20 14:24 UTC, Krayseer commented on src/main/java/ru/anykeyers/services/impl/SearchServiceImpl.java
> +                    .collect(Collectors.joining("\n\n"));
вынесено в UiContactMapper

2023-12-20 14:28 UTC, vpyzhyanov requested changes
По прежнему есть критичные замечания по ООП

2023-12-20 14:28 UTC, vpyzhyanov commented on src/main/java/ru/anykeyers/processor/state/impl/GroupStateProcessor.java
> +                case GroupEditActionKind.NAME -> {
Уместнее было определить enum, а значение получать так: `GroupEditActionKind.values()[num]`

2023-12-20 14:28 UTC, vpyzhyanov commented on src/main/java/ru/anykeyers/repository/file/FileContactRepository.java
> +        Optional.of(findByUsername(contact.getUsername()))
неуместное использование Optional. null тут никогда не будет. Похоже забыли убрать

2023-12-20 14:28 UTC, vpyzhyanov commented on src/main/java/ru/anykeyers/services/SearchService.java
> +public interface SearchService {
Не исправлено! Да и в этом сервисе нет ни одного метода, который связан с группами, зато в описании про них написано.

2023-12-20 14:28 UTC, vpyzhyanov commented on src/main/java/ru/anykeyers/service/SortContactService.java
> +public interface SortContactService {
Опять тёмная сторона ООП. Размазали ответственность. У вас есть сервис `Сервис для работы с контактами`, но по какой-то причине сортировка **контактов** никак не связана с **контактами**.

2023-12-20 14:28 UTC, vpyzhyanov commented on src/main/java/ru/anykeyers/service/FilterContactService.java
> +public interface FilterContactService {
ещё сильнее размазали ответственность

2023-12-20 14:28 UTC, vpyzhyanov commented on src/main/java/ru/anykeyers/service/SearchService.java
> +public interface SearchService {
нереально сильно размазали

2023-12-20 14:28 UTC, vpyzhyanov commented on src/main/java/ru/anykeyers/service/DataRetrievalService.java
> +public interface DataRetrievalService {
А тут сразу 2 тёмные стороны сразу. И всё та же размазанная ответственность и класс тянет на себе слишком много, работает и с контактами и с группами

2023-12-20 14:28 UTC, vpyzhyanov commented on src/main/java/ru/anykeyers/processor/state/impl/OperationStateProcessor.java
> +            return getUiContactsInfo(contacts);
не самое удачное имя метода. Операция 'get' обычно подразумевает возвращение какого-то объекта или свойства. Тут же вы преобразуете объект в строку. Лучше подойдёт `toFormattedString` или 'formatContacts' или просто 'format'

2023-12-20 14:28 UTC, vpyzhyanov commented on src/main/java/ru/anykeyers/service/impl/UserStateServiceImpl.java
> +        return stateInfoByUsername.get(user.getUsername());
это всё можно сделать в одну строчку так: `stateInfoByUsername.computeIfAbsent(user.getUsername(), s -> new StateInfo());`

2023-12-20 14:39 UTC, Krayseer commented on src/main/java/ru/anykeyers/service/SortContactService.java
> +public interface SortContactService {
Согласен, исправим

2023-12-20 14:40 UTC, Krayseer commented on src/main/java/ru/anykeyers/repository/file/FileContactRepository.java
> +        Optional.of(findByUsername(contact.getUsername()))
забыли убрать

2023-12-20 14:40 UTC, Krayseer commented on src/main/java/ru/anykeyers/processor/state/impl/GroupStateProcessor.java
> +                case GroupEditActionKind.NAME -> {
казалось что пробег по всем элементам будет затратный

2023-12-20 14:40 UTC, Krayseer commented on src/main/java/ru/anykeyers/service/FilterContactService.java
> +public interface FilterContactService {
Исправим

2023-12-20 14:40 UTC, Krayseer commented on src/main/java/ru/anykeyers/service/SearchService.java
> +public interface SearchService {
Исправим

2023-12-20 14:41 UTC, Krayseer commented on src/main/java/ru/anykeyers/service/DataRetrievalService.java
> +public interface DataRetrievalService {
Исправим

2023-12-20 14:41 UTC, Krayseer commented on src/main/java/ru/anykeyers/processor/state/impl/OperationStateProcessor.java
> +            return getUiContactsInfo(contacts);
поправим

2023-12-20 14:41 UTC, Krayseer commented on src/main/java/ru/anykeyers/service/impl/UserStateServiceImpl.java
> +        return stateInfoByUsername.get(user.getUsername());
поправим

2023-12-21 07:45 UTC, vpyzhyanov commented
Ребята, вы разве хотите лишиться даже уже полученных баллов за gti? Обнаружен прямой коммит в ветку task2

![image](https://github.com/Krayseer/contacter/assets/71599019/e18be11b-58a2-404b-90ba-0218cf4dc83f)

В третьей задаче рекомендую личные ветки тоже отребейзить (может даже повторно смёрджить), чтобы все коммиты и ветки выглядели как положено.

2023-12-21 09:26 UTC, vpyzhyanov requested changes
Задача принята. Как исправите последние замечания, можете мёрджить.

2023-12-21 09:26 UTC, vpyzhyanov commented on src/main/java/ru/anykeyers/common/Utils.java
> +    public Enum<?> getEnumKindByField(Enum<?>[] enumerate, String field) {
Почему же вы не используете дженерики там где они нужны?

```java
public <T extends Enum<T>> Enum<T> getEnumKindByField(Enum<T>[] enumerate, String field) {
```

И никаких кастов делать не надо!

2023-12-21 09:26 UTC, vpyzhyanov commented on src/main/java/ru/anykeyers/processor/state/impl/GroupStateProcessor.java
> +                case GroupEditActionKind.NAME -> {
Какой пробег? Где здесь пробег по всем элементам? В упор такого не вижу)

2023-12-21 09:26 UTC, vpyzhyanov commented on src/main/java/ru/anykeyers/common/Utils.java
> +public final class Utils {
Не бывает просто утилитарных классов, все утилиты должны быть разделены по группам находится в своих классах. Например `EnumUtils`

2023-12-21 09:26 UTC, vpyzhyanov commented on src/main/java/ru/anykeyers/common/Utils.java
> +            throw new InvalidNumberFormat();
Нет ни одной причины по которой вы должны создать свой тип исключения. Единственная причина создать своё исключение - чтобы его перехватить. Но у вас этого нет. Вы им всё равно не пользуетесь. Могли просто добавить сообщение ` throw new IllegalArgumentException("???", numberFormatException);` или, если стек сохранять не нужно, то просто ` throw new NumberFormatException("???");`

2023-12-21 09:26 UTC, vpyzhyanov commented on src/main/java/ru/anykeyers/common/Utils.java
> +            throw new BadArgumentException();
аналогично

2023-12-21 09:26 UTC, vpyzhyanov commented on src/main/java/ru/anykeyers/service/impl/UserStateServiceImpl.java
> +        return stateInfoByUsername.get(user.getUsername());
> это всё можно сделать в **одну** строчку

Я смотрю вы бездумно принимаете предложения, да и невнимательно читаете комментарий. И даже не видите к какой строчке написано замечание. Ну JavaDoc даже не потрудились почитать.

В общем убирайте этот `stateInfoByUsername.get(user.getUsername())` отсюда. computeIfAbsent уже возвращает элемент.

2023-12-21 09:53 UTC, Krayseer commented on src/main/java/ru/anykeyers/common/Utils.java
> +    public Enum<?> getEnumKindByField(Enum<?>[] enumerate, String field) {
это то что нужно! спасибо!

2023-12-21 09:54 UTC, Krayseer commented on src/main/java/ru/anykeyers/common/Utils.java
> +public final class Utils {
Поправим

2023-12-21 09:54 UTC, Krayseer commented on src/main/java/ru/anykeyers/common/Utils.java
> +            throw new InvalidNumberFormat();
хорошо, будет поправлено

2023-12-21 11:18 UTC, merged